SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH 
from MEMBER_PROFILE 
where MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL AND GENDER ='W' ORDER BY MEMBER_ID ASC;

//DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') = 출력값을 1993-03-26 형식으로 나오게 한다.
//MONTH(DATE_OF_BIRTH) = 3 1993-03-26에서 월이 3인지 확인
//TLNO IS NOT NULL 특정컬럼(TLNO)의 값이 NULL이 아닌 값만 
